# Generated by Django 4.0.4 on 2022-05-22 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_match_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='', max_length=1000, verbose_name='Wiadomość')),
                ('confirmation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='game.confirmation', verbose_name='Potwierdzenie')),
            ],
        ),
    ]
