# Generated by Django 4.0.4 on 2022-05-23 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0005_confirmationmessage_author_confirmationmessage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmation',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Odrzucony przez'),
        ),
    ]
