# Generated by Django 4.0.4 on 2022-06-07 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_confirmation_rejected_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='match_status',
        ),
    ]
